import { CircleHelp, Layers3, Rocket, ServerCog } from 'lucide-react'

import {
  ClaudeLogo,
  DiscordLogo,
  GlmLogo,
  GeminiLogo,
  OpenAILogo,
  TelegramLogo,
  WhatsAppLogo,
} from '../components/logos'
import { annualBillingMultiplier, channelCatalog, modelCatalog, planCatalog } from './catalog'
import type {
  AuthFormState,
  ComparisonPage,
  CreateUserFormState,
  FaqItem,
  Feature,
  GuideChannel,
  GuideContent,
  LegalSection,
  NavItem,
  Option,
  Plan,
  ResourcePage,
  SolutionPage,
} from '../app-types'

export const supportLinkHref = 'https://github.com/ruvnet/ruflo/issues'
export const supportLinkLabel = 'Ruflo GitHub Issues'
export const sourceRepositoryHref = 'https://github.com/ruvnet/ruflo'
export const supportEmailHref = 'mailto:support@aigeamy.com'
export const supportEmailLabel = 'support@aigeamy.com'

export const navItems: NavItem[] = [
  { href: '#features', label: 'Capabilities', icon: Layers3 },
  { href: '#solutions', label: 'Workflows', icon: Layers3 },
  { href: '#compare', label: 'Evaluate', icon: CircleHelp },
  { href: '/plans', label: 'Pricing', icon: Rocket },
  { href: '/console', label: 'Console', icon: ServerCog },
  { href: '#faq', label: 'FAQ', icon: CircleHelp },
]

export const privacySections: LegalSection[] = [
  {
    title: 'Scope and overview',
    paragraphs: [
      'This Privacy Policy explains how Ruflo AI processes information when visitors use the website, create an account, select a hosted workspace plan, pay for access, open the console, contact support, or use related APIs and operational features.',
      'The service is designed for hosted Ruflo workspaces, orchestration setup, checkout, provisioning, console access, and support. Some information is required so those workflows can operate reliably.',
    ],
  },
  {
    title: 'Information we collect',
    paragraphs: ['We collect information you provide directly, information produced by your use of the service, and limited technical data generated by normal website and API operation.'],
    bullets: [
      'Account and contact information such as name, email address, account role, and login state.',
      'Order and billing information such as selected plan, billing cycle, model route, workspace count, payment status, order identifiers, and timestamps.',
      'Workspace configuration information such as selected entrypoint, provisioning status, console links, runtime labels, and operational metadata.',
      'Optional credentials or tokens you submit when connecting an external coding tool or workspace entrypoint.',
      'Usage and diagnostic data such as page events, request timestamps, browser metadata, referrer context, and error information used for security and troubleshooting.',
    ],
  },
  {
    title: 'How we use information',
    paragraphs: ['We use information to operate, secure, improve, support, and enforce the service.'],
    bullets: [
      'To create checkout sessions, reconcile payments, and maintain order records.',
      'To provision hosted Ruflo workspaces and show launch state inside the console.',
      'To preserve workspace choices, entrypoint preferences, and account state.',
      'To respond to support requests and investigate payment or provisioning issues.',
      'To detect fraud, abuse, unauthorized access, and activity that could harm the service or other users.',
    ],
  },
  {
    title: 'Credentials and workspace data',
    paragraphs: [
      'Some workflows may involve API tokens, tool credentials, repository context, memory configuration, or other sensitive workspace material. We limit access to what is needed for the selected service function and use technical controls intended to reduce unnecessary exposure.',
      'No internet service can guarantee perfect security. You should submit only credentials and workspace material that you are authorized to use with the service.',
    ],
  },
  {
    title: 'Payments and providers',
    paragraphs: [
      'Payment processing is handled by third-party payment providers. Checkout pages, payment verification, tax handling, card fields, and billing decisions may be controlled by those providers.',
      'We may share order identifiers, plan details, price information, return URLs, and limited transaction metadata with payment providers so checkout and payment confirmation can work.',
    ],
  },
  {
    title: 'Retention, choices, and contact',
    paragraphs: [
      'We retain information for as long as reasonably necessary for account administration, payment records, workspace operations, support, fraud prevention, dispute handling, and legal or operational obligations.',
      `For privacy questions, contact ${supportEmailLabel} or open an issue at ${supportLinkHref}.`,
    ],
  },
]

export const termsSections: LegalSection[] = [
  {
    title: 'Acceptance of terms',
    paragraphs: [
      'These Terms of Service govern access to and use of Ruflo AI, including the website, checkout flow, console, hosted workspace provisioning, APIs, support, and related operational features.',
      'By accessing or using the service, you agree to these Terms. If you do not agree, do not use the service.',
    ],
  },
  {
    title: 'Nature of the service',
    paragraphs: [
      'Ruflo AI provides a hosted launch and operations layer for Ruflo-inspired agent orchestration workflows. The service helps users select a plan, initiate payment, provision workspace capacity, and manage access through a console.',
      'Features, supported tools, model routes, payment providers, launch methods, and workspace capabilities may change over time as the service evolves.',
    ],
  },
  {
    title: 'Orders and payment',
    paragraphs: [
      'Submitting a checkout request or selecting a plan does not guarantee successful payment, immediate provisioning, uninterrupted service, or continued availability of every integration.',
      'Prices and plan details are shown on the site. Final checkout availability, card acceptance, tax handling, currency handling, and payment approval remain subject to the payment provider.',
    ],
  },
  {
    title: 'Workspace responsibility',
    paragraphs: [
      'You are responsible for the repositories, credentials, prompts, tasks, data, and instructions you submit to a workspace. You must have the rights and authority required to use that material with the service.',
      'You may not use the service for unlawful, abusive, infringing, deceptive, or harmful activity, or to bypass access controls, payment controls, repository permissions, or security boundaries.',
    ],
  },
  {
    title: 'Third-party tools',
    paragraphs: [
      'The service may rely on third-party infrastructure, payment systems, repositories, model providers, coding tools, and communication services. We do not control those third-party services and are not responsible for their outages, policy changes, risk decisions, or limitations.',
    ],
  },
  {
    title: 'Disclaimers and limitation of liability',
    paragraphs: [
      'The service is provided on an as-is and as-available basis. We do not warrant that it will be uninterrupted, error-free, perfectly secure, or suitable for every repository, workflow, browser, network, payment provider, or model provider.',
      'To the maximum extent permitted by law, Ruflo AI and its operators will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost revenue, profit, goodwill, opportunity, use, or data.',
    ],
  },
  {
    title: 'Changes and contact',
    paragraphs: [
      'We may update these Terms by posting a revised version on the website. Continued use after an update means you accept the revised Terms.',
      `For questions about these Terms, contact ${supportEmailLabel} or open an issue at ${supportLinkHref}.`,
    ],
  },
]

export const models: Option[] = modelCatalog.map((model) => ({
  ...model,
  icon:
    model.id.startsWith('glm')
      ? <GlmLogo />
      : model.id.startsWith('claude')
        ? <ClaudeLogo />
        : model.id.startsWith('gpt')
          ? <OpenAILogo />
          : <GeminiLogo />,
}))

export const channels: Option[] = channelCatalog.map((channel) => ({
  ...channel,
  icon:
    channel.id === 'telegram'
      ? <TelegramLogo />
      : channel.id === 'discord'
        ? <DiscordLogo />
        : <WhatsAppLogo />,
}))

export const channelBadges = ['Claude Code', 'Codex', 'MCP tools', 'Memory', 'RAG', 'Swarm']

export const features: Feature[] = [
  {
    title: 'Multi-agent orchestration',
    description: (
      <>
        Build a <strong>goal-driven swarm</strong> where planning, execution, review, and handoff can be split across
        specialized agents instead of one overloaded prompt.
      </>
    ),
  },
  {
    title: 'Claude Code and Codex ready',
    description: (
      <>
        Ruflo is useful when your team already lives in coding agents. Launch with an entrypoint for <strong>Claude
        Code</strong>, <strong>Codex</strong>, or the hosted UI and keep the operational layer in one place.
      </>
    ),
  },
  {
    title: 'Memory and RAG for repeat work',
    description: (
      <>
        Preserve reusable context, project knowledge, and retrieval-backed notes so recurring work improves instead of
        restarting from a blank session.
      </>
    ),
  },
  {
    title: 'Goal Planner UI',
    description:
      'Use a structured launch surface for goals, routes, checkpoints, and workspace state rather than asking every user to assemble the orchestration stack by hand.',
  },
  {
    title: 'Federated team patterns',
    description:
      'Ruflo is strongest when several operators need a shared way to delegate tasks, review outputs, and reuse successful workflows across projects.',
  },
  {
    title: 'Hosted checkout and console',
    description:
      'This SaaS layer adds pricing, payment, provisioning, and console workflows around the open-source project so customers can move from evaluation to a working workspace faster.',
  },
]

export const plans: Plan[] = planCatalog

export const faqs: FaqItem[] = [
  {
    question: 'What is Ruflo AI?',
    answer:
      'Ruflo AI is a hosted workspace service built around Ruflo-style multi-agent orchestration. It gives teams a faster path to run goal planning, coding-agent delegation, memory, RAG, and review workflows without building the operations layer first.',
  },
  {
    question: 'Does this replace the open-source Ruflo project?',
    answer:
      'No. The GitHub project remains the source reference. This site packages the useful operating path around it: plan selection, checkout, provisioning, console access, and hosted workspace management.',
  },
  {
    question: 'Why is the yearly plan selected by default?',
    answer:
      'Ruflo is most valuable when memory, workflows, and review patterns compound over time. Yearly billing is selected by default and is priced at 50% off the equivalent monthly total.',
  },
  {
    question: 'Which plan should most teams choose?',
    answer:
      'Growth is the default because it fits the most common rollout: several workspaces, active review loops, and enough capacity to test Ruflo with real repository work rather than a single demo.',
  },
  {
    question: 'Can I use Ruflo with Codex or Claude Code?',
    answer:
      'Yes. The service is designed for teams comparing or combining Codex, Claude Code, and Ruflo UI workflows. The goal is to make agent delegation easier to operate, not to lock you into one interface.',
  },
  {
    question: 'How do I check whether Ruflo is legit before paying?',
    answer: (
      <>
        Read the{' '}
        <a href="/resources/is-ruflo-legit" className="inline-link">
          evaluation checklist
        </a>{' '}
        and inspect the{' '}
        <a href={sourceRepositoryHref} className="inline-link" target="_blank" rel="noreferrer">
          source repository
        </a>
        . Look for concrete architecture, setup clarity, issue history, and whether the workflow maps to the kind of
        work your team actually repeats.
      </>
    ),
  },
]

export const solutionPages: SolutionPage[] = [
  {
    href: '/solutions/codebase-swarms',
    label: 'Codebase Swarms',
    eyebrow: 'Workflow',
    title: 'Run Ruflo workspaces for codebase planning, execution, and review',
    summary:
      'Give engineering teams a structured way to split repository work into planner, implementer, reviewer, and follow-up roles while keeping checkout and workspace operations handled.',
    definition:
      'A Ruflo codebase swarm is a coordinated set of agents and human checkpoints around a repository goal. The hosted workspace helps the team move from goal definition to usable execution without hand-building every operational step.',
    facts: [
      'Useful for repo triage, implementation planning, refactor review, and release preparation.',
      'Works well beside coding agents such as Codex and Claude Code.',
      'Keeps plan, execution, memory, and review closer together than a loose collection of chats.',
      'Hosted provisioning reduces the gap between evaluating Ruflo and using it on real work.',
    ],
    bestFor: ['Engineering teams with recurring repository work', 'Founders who need faster code review loops', 'Operators coordinating several AI coding tools'],
    notFor: ['One-off prompts with no need for review', 'Teams that only want a generic chatbot', 'Projects where repository access cannot be granted to any hosted workflow'],
    outcomes: ['Clearer goal decomposition', 'Faster handoff between coding agents', 'More reusable review and planning patterns'],
    workflow: [
      'Choose the model route and hosted workspace tier',
      'Launch the workspace and connect the first coding entrypoint',
      'Use Ruflo to plan, execute, review, and preserve what worked for the next run',
    ],
    conclusion:
      'Use this path when the value is not another answer, but a repeatable operating loop around real codebase work.',
    faqs: [
      {
        question: 'Can Ruflo coordinate more than one coding agent?',
        answer:
          'That is one of the main reasons to use it. The workflow is built around delegation, review, and state rather than treating every model session as a separate island.',
      },
      {
        question: 'Do I need to move my repository into Ruflo?',
        answer:
          'No. The hosted service is meant to operate around your existing code workflow. You decide what repository context and credentials are appropriate to connect.',
      },
      {
        question: 'Is this useful for solo builders?',
        answer:
          'Yes, especially when one person is juggling planning, implementation, QA, and release notes. Ruflo gives those roles more structure.',
      },
    ],
  },
  {
    href: '/solutions/research-memory',
    label: 'Research Memory',
    eyebrow: 'Workflow',
    title: 'Use Ruflo for research loops that need memory, retrieval, and follow-up',
    summary:
      'Turn recurring research, documentation, and evaluation work into a workspace with retrieval, structured goals, and reusable operating memory.',
    definition:
      'Ruflo research memory is a workflow for teams that repeatedly inspect sources, compare tools, write briefs, and need the next run to remember what mattered in the previous one.',
    facts: [
      'Useful for repository evaluation, tool comparison, implementation notes, and competitive research.',
      'RAG and memory help preserve stable knowledge without bloating every prompt.',
      'The hosted console gives teams a clearer place to return after checkout and launch.',
      'Works best when research becomes a repeatable operating process.',
    ],
    bestFor: ['Product teams evaluating developer tools', 'Engineering leads comparing agent workflows', 'Analysts producing recurring technical briefs'],
    notFor: ['One-off summaries with no future reuse', 'Workflows that cannot reference external sources', 'Teams that want only static documentation'],
    outcomes: ['More consistent source review', 'Less repeated setup', 'Cleaner memory between research cycles'],
    workflow: [
      'Define the research goal and model route',
      'Launch a workspace that can preserve useful context',
      'Use the console to revisit outputs, refine memory, and run the next cycle',
    ],
    conclusion:
      'This path fits teams whose research work compounds: the second run should benefit from the first.',
    faqs: [
      {
        question: 'Is Ruflo only for coding?',
        answer:
          'No. Coding is a strong use case, but Ruflo-style orchestration also fits research, evaluation, documentation, and recurring operational briefs.',
      },
      {
        question: 'What makes memory useful here?',
        answer:
          'The useful part is not storing everything. It is preserving the stable context, decisions, source patterns, and workflow notes that make the next run faster.',
      },
      {
        question: 'Can I still inspect sources myself?',
        answer:
          'Yes. Ruflo should make review easier, not hide it. Strong research workflows keep sources and reasoning visible enough for humans to evaluate.',
      },
    ],
  },
  {
    href: '/solutions/team-agent-ops',
    label: 'Team Agent Ops',
    eyebrow: 'Workflow',
    title: 'Standardize how a team launches, pays for, and reviews agent work',
    summary:
      'Use Ruflo AI when the hard part is not trying one agent, but making agent work repeatable across people, repositories, reviews, and billing.',
    definition:
      'Team agent operations means treating AI agent work as an operational surface: who launches, who reviews, which workspace owns memory, how payment is handled, and how successful workflows become reusable.',
    facts: [
      'The hosted layer gives buyers a clear path from plan choice to checkout to console.',
      'Middle-tier yearly billing is optimized for teams that expect ongoing usage.',
      'Shared workflows reduce the mess of scattered prompts and private experiments.',
      'Ruflo fits teams comparing Codex, Claude Code, and UI-driven agent orchestration.',
    ],
    bestFor: ['Small teams adopting agent workflows', 'Agencies running repeatable client delivery', 'Technical operators who need purchase and provisioning in one place'],
    notFor: ['Teams with no recurring agent work', 'Organizations that require fully self-hosted infrastructure from day one', 'Pure chat support use cases'],
    outcomes: ['Cleaner rollout decisions', 'A shared console for orders and workspaces', 'Better continuity between experiments and production usage'],
    workflow: [
      'Pick Growth yearly for the common team rollout',
      'Complete hosted checkout through Creem',
      'Return to the homepage or console and continue provisioning from the same service surface',
    ],
    conclusion:
      'Use this path when Ruflo needs to become a service your team can buy, revisit, and operate, not just a repository someone starred.',
    faqs: [
      {
        question: 'Why package Ruflo as a SaaS?',
        answer:
          'Because many teams want the value of the orchestration model before they want to own every deployment, payment, and operations detail themselves.',
      },
      {
        question: 'Can a team still self-host later?',
        answer:
          'Yes. Hosted usage can be a practical way to validate the workflow before deciding whether deeper self-hosting is worth the engineering time.',
      },
      {
        question: 'Does payment complete inside the site?',
        answer:
          'Checkout opens as a hosted Creem payment session. After successful payment, the return URL brings the customer back to the Ruflo AI site.',
      },
    ],
  },
]

export const comparisonPages: ComparisonPage[] = [
  {
    href: '/compare/ruflo-vs-single-agent-tools',
    label: 'Single-Agent Tools',
    eyebrow: 'Evaluate',
    title: 'Ruflo vs single-agent coding tools',
    summary:
      'Single-agent tools are excellent for focused work. Ruflo becomes useful when a team needs goal planning, delegation, memory, review, and repeatable handoff around those tools.',
    alternativeName: 'Single-agent coding tool',
    chooseLaunch: [
      'You need planner, executor, reviewer, and memory roles around code work',
      'You compare Codex, Claude Code, and UI-based workflows in the same operating model',
      'You want checkout, workspace provisioning, and console follow-up handled for customers',
    ],
    chooseAlternative: [
      'You only need one agent to edit a small change',
      'You do not need persistent memory or review workflow',
      'Your team is not ready to operate multi-agent delegation',
    ],
    rows: [
      {
        label: 'Work shape',
        launch: 'Goal-oriented orchestration with handoff between agent roles',
        alternative: 'One agent session handles most of the work directly',
      },
      {
        label: 'Memory',
        launch: 'Designed for reusable project and workflow memory',
        alternative: 'Often depends on the current session or manual notes',
      },
      {
        label: 'Team operation',
        launch: 'Plan, payment, provisioning, console, and review can live together',
        alternative: 'Great for individual execution, less complete as a service layer',
      },
      {
        label: 'Best use',
        launch: 'Recurring work across repositories, agents, and operators',
        alternative: 'Focused coding tasks with a clear local scope',
      },
    ],
    faqs: [
      {
        question: 'Does Ruflo replace Codex or Claude Code?',
        answer:
          'No. Ruflo is better thought of as orchestration and workspace structure around coding agents. It can make those tools easier to coordinate.',
      },
      {
        question: 'When is a single-agent workflow enough?',
        answer:
          'When the task is small, local, and does not need durable memory, reviewer handoff, or a repeatable process.',
      },
      {
        question: 'Why launch hosted Ruflo instead of wiring this manually?',
        answer:
          'Hosted launch is useful when the buyer values speed to a working workspace more than owning every piece of setup on day one.',
      },
    ],
  },
  {
    href: '/compare/hosted-ruflo-vs-self-hosting',
    label: 'Self-Hosting',
    eyebrow: 'Evaluate',
    title: 'Hosted Ruflo vs self-hosting from GitHub',
    summary:
      'Self-hosting gives maximum control. Hosted Ruflo is the better first step when the priority is validating workflows, payment, provisioning, and team usage quickly.',
    alternativeName: 'Self-hosted Ruflo',
    chooseLaunch: [
      'You want a working hosted path with checkout and console management',
      'You need to validate value before assigning infrastructure time',
      'You want customers to buy and start without reading every setup detail first',
    ],
    chooseAlternative: [
      'You need full infrastructure ownership immediately',
      'Your compliance requirements forbid hosted workspaces',
      'Your team is ready to maintain the full runtime and deployment layer',
    ],
    rows: [
      {
        label: 'Time to first use',
        launch: 'Shorter path from evaluation to payment to workspace',
        alternative: 'Depends on local setup, runtime choices, and operator skill',
      },
      {
        label: 'Control',
        launch: 'Managed service surface with opinionated defaults',
        alternative: 'Full control over infrastructure and code changes',
      },
      {
        label: 'Customer conversion',
        launch: 'Built around pricing, checkout, and return flow',
        alternative: 'Requires a separate commercial layer',
      },
      {
        label: 'Best use',
        launch: 'Commercial validation and team rollout',
        alternative: 'Deep customization and internal infrastructure ownership',
      },
    ],
    faqs: [
      {
        question: 'Should technical teams still read the GitHub repository?',
        answer:
          'Yes. Reading the source helps you understand the architecture and risk. Hosted Ruflo exists to make the buying and launch path faster once the fit is clear.',
      },
      {
        question: 'Can hosted usage come before self-hosting?',
        answer:
          'That is often the cleanest sequence: validate the workflow, then decide whether the infrastructure deserves deeper ownership.',
      },
      {
        question: 'What is the biggest hosted tradeoff?',
        answer:
          'You accept managed defaults. That is worthwhile when speed and conversion matter more than controlling every deployment detail immediately.',
      },
    ],
  },
]

const rufoNameLookupPages: ResourcePage[] = [
  {
    href: '/chris-rufo-website',
    label: 'Chris Rufo Website',
    eyebrow: 'Source guide',
    title: 'Chris Rufo website: official links and name check',
    summary:
      'A quick source guide for people who searched for Chris Rufo and want the right official website, biography, article archive, and social profile without confusing him with Ruflo AI.',
    definition:
      'Chris Rufo usually refers to Christopher F. Rufo, the writer, filmmaker, and activist. Ruflo AI is a separate hosted multi-agent workspace service with a similar-looking name, and it is not affiliated with Christopher F. Rufo.',
    primaryAction: {
      label: "Open Christopher Rufo's website",
      href: 'https://christopherrufo.com/about',
      external: true,
    },
    showOnHome: false,
    sections: [
      {
        title: 'Start with the official site',
        body:
          'The most direct place to verify his own current biography and publication hub is christopherrufo.com. Use that first when you need his self-published work, subscription page, contact path, or current positioning.',
        bullets: ['Official site: christopherrufo.com', 'Author spelling: Christopher F. Rufo', 'Common short form: Chris Rufo'],
      },
      {
        title: 'Use institutional profiles for context',
        body:
          'For a second source, compare the City Journal and Manhattan Institute pages. Those pages identify his roles, article archive, and public policy work more clearly than a general web search result.',
      },
      {
        title: 'If you meant Ruflo AI',
        body:
          'Ruflo AI is about hosted multi-agent workspaces, Codex, Claude Code, memory, RAG, and workspace checkout. The spelling overlap can be confusing, but the subjects are unrelated.',
      },
    ],
    checklist: [
      'Check christopherrufo.com for his own site',
      'Check City Journal for the author archive',
      'Check Manhattan Institute for institutional biography',
      'Use this site only if you meant Ruflo AI workspaces',
    ],
    conclusion:
      'If you were looking for Christopher F. Rufo, use the official source links above. If you were looking for Ruflo AI, continue with the workspace launch path on this site.',
    faqs: [
      {
        question: 'Is Chris Rufo connected to Ruflo AI?',
        answer:
          'No. Christopher F. Rufo and Ruflo AI are separate subjects. This page exists to help visitors who may have reached Ruflo AI because the names look similar.',
      },
      {
        question: 'What is the best Chris Rufo website to open first?',
        answer:
          'Start with christopherrufo.com for his own publication hub, then use City Journal and Manhattan Institute for institutional profiles and article context.',
      },
      {
        question: 'Why does this page mention Ruflo AI?',
        answer:
          'Because visitors sometimes land here after searching a similar-looking name. The page helps them leave with the right source instead of guessing.',
      },
    ],
  },
  {
    href: '/christopher-rufo-website',
    label: 'Christopher Rufo Website',
    eyebrow: 'Source guide',
    title: 'Christopher Rufo website and official source directory',
    summary:
      'A clean directory for the main Christopher F. Rufo sources: his own website, City Journal author page, Manhattan Institute profile, Wikipedia overview, and X profile.',
    definition:
      'Christopher Rufo searches are best handled by separating source types. His own website is useful for his direct writing and biography; institutional profiles are useful for roles and archives; Wikipedia is useful for a broad reference overview.',
    primaryAction: {
      label: "Open Christopher Rufo's website",
      href: 'https://christopherrufo.com/about',
      external: true,
    },
    showOnHome: false,
    sections: [
      {
        title: 'Source order that avoids confusion',
        body:
          'Use the official site for his direct publication hub, the City Journal page for article archive context, the Manhattan Institute page for institutional biography, and Wikipedia for a broad summary with references.',
        bullets: [
          'Official site: christopherrufo.com/about',
          'City Journal: city-journal.org/person/christopher-f-rufo',
          'Manhattan Institute: manhattan.institute/person/christopher-f-rufo',
          'Wikipedia: en.wikipedia.org/wiki/Christopher_Rufo',
        ],
      },
      {
        title: 'When a profile is more useful than the website',
        body:
          'If you need a neutral source trail, use Wikipedia references and institutional profiles before relying on social posts. If you need his newest commentary, use his own site or verified X profile.',
      },
      {
        title: 'Name mismatch note',
        body:
          'Ruflo AI is not a Christopher Rufo project. It is a hosted agent-workspace product for teams using tools such as Codex and Claude Code.',
      },
    ],
    checklist: [
      'Confirm the spelling is Christopher F. Rufo',
      'Use the official website for direct work',
      'Use City Journal for author archive context',
      'Use Ruflo AI pages only for agent workspace research',
    ],
    conclusion:
      'The fastest path is to open the official Christopher F. Rufo site for his direct work, then cross-check City Journal or Manhattan Institute if you need institutional context.',
    faqs: [
      {
        question: 'Is christopherrufo.com the same as ruflo.online?',
        answer:
          'No. christopherrufo.com is associated with Christopher F. Rufo. ruflo.online is a separate Ruflo AI workspace service.',
      },
      {
        question: 'Which source is best for article history?',
        answer:
          'Use the City Journal author page when you want his City Journal writing in one place.',
      },
      {
        question: 'Which source is best for a quick overview?',
        answer:
          'Wikipedia can be useful for a broad overview, but cross-check important claims against primary or institutional sources.',
      },
    ],
  },
  {
    href: '/christopher-f-rufo-wikipedia',
    label: 'Rufo Wikipedia',
    eyebrow: 'Reference guide',
    title: 'Christopher F. Rufo Wikipedia guide and source cross-check',
    summary:
      'How to use the Christopher Rufo Wikipedia page responsibly: what it is good for, what to verify elsewhere, and how it differs from Ruflo AI.',
    definition:
      'The Christopher Rufo Wikipedia page is a general reference page about Christopher F. Rufo. It can help with dates, background, controversies, and source trails, but it should not be the only source for a current profile.',
    primaryAction: {
      label: 'Open Wikipedia overview',
      href: 'https://en.wikipedia.org/wiki/Christopher_Rufo',
      external: true,
    },
    showOnHome: false,
    sections: [
      {
        title: 'What Wikipedia is useful for',
        body:
          'Use Wikipedia to orient yourself quickly: full name, broad biography, education, books, public controversies, and references to reporting from other outlets.',
        bullets: ['Fast overview', 'Reference trail', 'Alternative spellings and context', 'Links to books and institutions'],
      },
      {
        title: 'What to verify elsewhere',
        body:
          'For current roles, newest articles, and active social posts, check the official website, City Journal author page, Manhattan Institute profile, or X profile directly.',
      },
      {
        title: 'Avoid the Ruflo/Rufo mix-up',
        body:
          'Ruflo AI is a product name for hosted multi-agent workspaces. Christopher F. Rufo is a public figure. A Wikipedia search about Rufo is not a product page for Ruflo AI.',
      },
    ],
    checklist: [
      'Use Wikipedia for orientation',
      'Open cited sources for important claims',
      'Use official profiles for current roles',
      'Check spelling before searching again',
    ],
    conclusion:
      'Wikipedia is best as a map, not the destination. Use it to find the source trail, then verify the specific detail you need on a primary or institutional page.',
    faqs: [
      {
        question: 'What is the Wikipedia page title?',
        answer:
          'The English Wikipedia page is titled Christopher Rufo and covers Christopher F. Rufo as a public figure.',
      },
      {
        question: 'Is Wikipedia the best source for current posts?',
        answer:
          'No. Use his official site or verified X profile for current posts, and use institutional pages for stable biography.',
      },
      {
        question: 'Does Ruflo AI maintain the Wikipedia page?',
        answer:
          'No. Ruflo AI is unrelated to Christopher F. Rufo and does not maintain that reference page.',
      },
    ],
  },
  {
    href: '/chris-rufo-city-journal',
    label: 'Chris Rufo City Journal',
    eyebrow: 'Author guide',
    title: 'Chris Rufo City Journal author page and article archive',
    summary:
      'A shortcut for finding Christopher F. Rufo at City Journal, understanding what the author page contains, and separating that archive from Ruflo AI.',
    definition:
      'Chris Rufo City Journal searches usually point to the Christopher F. Rufo author page at City Journal, where his role and publication archive are grouped by the magazine.',
    primaryAction: {
      label: 'Open City Journal author page',
      href: 'https://www.city-journal.org/person/christopher-f-rufo',
      external: true,
    },
    showOnHome: false,
    sections: [
      {
        title: 'What the City Journal page gives you',
        body:
          'City Journal is useful when you want his magazine biography, contributing editor context, article archive, and related publication links in one place.',
        bullets: ['Author profile', 'Article archive', 'Magazine context', 'Linked X profile and institutional bio'],
      },
      {
        title: 'How to read the archive',
        body:
          'Start with the headline and publication date, then check whether the article is commentary, reporting, video, podcast, or magazine analysis. That distinction matters when citing or summarizing the work.',
      },
      {
        title: 'If you searched from Ruflo AI',
        body:
          'Ruflo AI has resource pages about agent workspaces and coding-agent workflows. The City Journal archive is a separate public-interest source about Christopher F. Rufo.',
      },
    ],
    checklist: [
      'Open the City Journal author page',
      'Check dates before citing older articles',
      'Distinguish articles from podcasts or video pages',
      'Use Ruflo AI only for workspace product information',
    ],
    conclusion:
      'Use City Journal when your goal is Christopher F. Rufo byline research. Use Ruflo AI when your goal is multi-agent workspace launch and operation.',
    faqs: [
      {
        question: 'Is Chris Rufo a City Journal contributor?',
        answer:
          'City Journal lists Christopher F. Rufo as a contributing editor and provides an author page for his work.',
      },
      {
        question: 'Is the City Journal page his personal website?',
        answer:
          'No. It is an author page on City Journal. His own publication hub is christopherrufo.com.',
      },
      {
        question: 'Is City Journal related to Ruflo AI?',
        answer:
          'No. City Journal and Ruflo AI are separate. The similar Rufo/Ruflo spelling is the only reason this clarification is useful here.',
      },
    ],
  },
  {
    href: '/who-is-christopher-rufo',
    label: 'Who Is Christopher Rufo',
    eyebrow: 'Background guide',
    title: 'Who is Christopher Rufo? Quick source-based overview',
    summary:
      'A concise overview for visitors trying to identify Christopher F. Rufo, find reliable source links, and avoid confusing him with Ruflo AI.',
    definition:
      'Christopher F. Rufo is commonly described by his official and institutional profiles as a writer, filmmaker, activist, senior fellow at the Manhattan Institute, and contributing editor of City Journal.',
    primaryAction: {
      label: 'Open Manhattan Institute profile',
      href: 'https://manhattan.institute/person/christopher-f-rufo',
      external: true,
    },
    showOnHome: false,
    sections: [
      {
        title: 'Fast identification',
        body:
          'The stable way to identify him is by full name and institutional roles: Christopher F. Rufo, senior fellow at the Manhattan Institute, contributing editor at City Journal, and public writer on critical race theory, DEI, cities, and institutional politics.',
        bullets: ['Full name: Christopher F. Rufo', 'Short name: Chris Rufo', 'Primary topics: culture, institutions, cities, education, and policy'],
      },
      {
        title: 'Best source for each need',
        body:
          'Use the Manhattan Institute page for role context, City Journal for articles, christopherrufo.com for his own publication hub, X for current posts, and Wikipedia for a broad overview with references.',
      },
      {
        title: 'Why you may have landed here',
        body:
          'Ruflo AI sounds similar to Rufo, but it is a product site for hosted agent workspaces. It is not a biography site and is not affiliated with Christopher F. Rufo.',
      },
    ],
    checklist: [
      'Use full name when searching',
      'Pick the source type that matches your question',
      'Cross-check current claims against primary pages',
      'Switch to Ruflo AI pages only for agent workspace research',
    ],
    conclusion:
      'For a quick answer, identify him through the Manhattan Institute or City Journal pages, then use his own site or X profile when you need current work.',
    faqs: [
      {
        question: 'What does Christopher Rufo do?',
        answer:
          'Public profiles describe him as a writer, filmmaker, activist, senior fellow at the Manhattan Institute, and contributing editor of City Journal.',
      },
      {
        question: 'What topics is he known for?',
        answer:
          'His public profiles and article archive emphasize critical race theory, DEI, education, cities, homelessness, addiction, crime, and related policy debates.',
      },
      {
        question: 'Is this page a biography from Ruflo AI?',
        answer:
          'It is a source guide and name clarification page. It points visitors to better sources rather than pretending Ruflo AI is an authority on him.',
      },
    ],
  },
  {
    href: '/christopher-ruffo-journalist',
    label: 'Christopher Ruffo Journalist',
    eyebrow: 'Spelling guide',
    title: 'Christopher Ruffo journalist: correct spelling and source links',
    summary:
      'A spelling correction page for people searching Christopher Ruffo journalist who likely mean Christopher F. Rufo, with links to the right official sources.',
    definition:
      'Christopher Ruffo with two f characters is usually a misspelling in this search context. The public figure most people are looking for is Christopher F. Rufo.',
    primaryAction: {
      label: 'Open corrected official site',
      href: 'https://christopherrufo.com/about',
      external: true,
    },
    showOnHome: false,
    sections: [
      {
        title: 'Correct the spelling before searching again',
        body:
          'Search engines may understand the typo, but source verification is easier when you search the exact spelling: Christopher F. Rufo or Chris Rufo.',
        bullets: ['Likely typo: Christopher Ruffo', 'Correct spelling: Christopher F. Rufo', 'Short search: Chris Rufo'],
      },
      {
        title: 'Journalist and author sources',
        body:
          'Use christopherrufo.com for his own publication hub, City Journal for his article archive, and Manhattan Institute for an institutional profile.',
      },
      {
        title: 'Do not confuse it with Ruflo',
        body:
          'Ruflo AI has an l in the product name. It is not a spelling variation of Rufo or Ruffo; it is a separate agent-workspace service.',
      },
    ],
    checklist: [
      'Search Christopher F. Rufo',
      'Use City Journal for the byline archive',
      'Use Manhattan Institute for current role context',
      'Use Ruflo AI only if you meant agent workspaces',
    ],
    conclusion:
      'The corrected search is Christopher F. Rufo. Use the official site and institutional profiles for source verification, then return to Ruflo AI only if you intended the workspace product.',
    faqs: [
      {
        question: 'Is Christopher Ruffo the correct spelling?',
        answer:
          'For this public figure, the usual spelling is Christopher F. Rufo, with one f in Rufo.',
      },
      {
        question: 'Is Christopher Rufo a journalist?',
        answer:
          'His own and institutional profiles describe him as a writer, filmmaker, and activist, and City Journal hosts his contributing editor author page.',
      },
      {
        question: 'Is Ruflo a typo for Rufo?',
        answer:
          'No. Ruflo AI is a separate product name for hosted multi-agent workspaces.',
      },
    ],
  },
  {
    href: '/rufo-twitter',
    label: 'Rufo Twitter',
    eyebrow: 'Profile guide',
    title: 'Rufo Twitter/X profile: how to find the verified source',
    summary:
      'A quick guide for finding Christopher F. Rufo on X, checking the handle, and knowing when to use social posts versus more stable profile pages.',
    definition:
      'Rufo Twitter searches usually refer to Christopher F. Rufo on X. City Journal and Manhattan Institute link to the X profile at x.com/realchrisrufo.',
    primaryAction: {
      label: 'Open X profile',
      href: 'https://x.com/realchrisrufo',
      external: true,
    },
    showOnHome: false,
    sections: [
      {
        title: 'Handle to check',
        body:
          'The linked X profile from City Journal and Manhattan Institute uses the handle @realchrisrufo. Use those institutional pages as a safer way to confirm you have the right profile.',
        bullets: ['X handle: @realchrisrufo', 'Cross-check from City Journal', 'Cross-check from Manhattan Institute'],
      },
      {
        title: 'When X is useful',
        body:
          'Use X for current posts, live reactions, and links he is sharing now. For biography, roles, or article archives, use the official site, City Journal, or Manhattan Institute.',
      },
      {
        title: 'Ruflo AI is separate',
        body:
          'Ruflo AI is not the Rufo X profile. If you are trying to launch a hosted multi-agent workspace, use the Ruflo AI product pages instead.',
      },
    ],
    checklist: [
      'Confirm the handle @realchrisrufo',
      'Use institutional links to avoid impersonation',
      'Use X for current posts, not stable biography',
      'Use Ruflo AI only for workspace product information',
    ],
    conclusion:
      'Open X when you need current posts, but use stable source pages when you need a reliable biography or article archive.',
    faqs: [
      {
        question: 'What is Chris Rufo on Twitter/X?',
        answer:
          'The X profile linked from City Journal and Manhattan Institute is @realchrisrufo.',
      },
      {
        question: 'Should I cite X for biography?',
        answer:
          'Use X for current posts. For biography, cite the official site, City Journal, Manhattan Institute, or a referenced overview.',
      },
      {
        question: 'Is Ruflo AI on that X profile?',
        answer:
          'No. The Rufo X profile is separate from Ruflo AI.',
      },
    ],
  },
  {
    href: '/christopher-rufo-city-journal',
    label: 'Christopher Rufo City Journal',
    eyebrow: 'Author guide',
    title: 'Christopher Rufo at City Journal: byline, topics, and source context',
    summary:
      'A practical guide to the Christopher F. Rufo City Journal author page, including what it verifies and when to use another source.',
    definition:
      'The Christopher F. Rufo City Journal page is an institutional author page. It is useful for byline verification, article discovery, and understanding how City Journal presents his work.',
    primaryAction: {
      label: 'Open City Journal profile',
      href: 'https://www.city-journal.org/person/christopher-f-rufo',
      external: true,
    },
    showOnHome: false,
    sections: [
      {
        title: 'What City Journal verifies',
        body:
          'The page identifies his City Journal role, links his work, and provides topic context around critical race theory, gender ideology, homelessness, addiction, crime, and urban decline.',
        bullets: ['Contributing editor context', 'Author archive', 'Topic framing', 'Related institutional links'],
      },
      {
        title: 'When to use another source',
        body:
          'Use christopherrufo.com for his own publication hub, Manhattan Institute for a scholar profile, Wikipedia for a broad overview, and X for current posts.',
      },
      {
        title: 'Ruflo AI context',
        body:
          'This page is here because Rufo and Ruflo look similar in search. Ruflo AI is a separate hosted workspace product and does not represent City Journal or Christopher F. Rufo.',
      },
    ],
    checklist: [
      'Use City Journal for article archive research',
      'Check publication dates and formats',
      'Cross-check role details with Manhattan Institute',
      'Use Ruflo AI pages for hosted agent workflows only',
    ],
    conclusion:
      'For Christopher F. Rufo articles, City Journal is the right starting point. For Ruflo AI workspaces, use the product pages on ruflo.online.',
    faqs: [
      {
        question: 'Where is the Christopher Rufo City Journal page?',
        answer:
          'The City Journal author page is at city-journal.org/person/christopher-f-rufo.',
      },
      {
        question: 'What topics appear in the City Journal profile?',
        answer:
          'The profile describes writing on critical race theory, gender ideology, homelessness, addiction, crime, and the decline of American cities.',
      },
      {
        question: 'Does this make Ruflo AI a City Journal project?',
        answer:
          'No. Ruflo AI is separate. This page only helps visitors route themselves to the right source.',
      },
    ],
  },
]

export const resourcePages: ResourcePage[] = [
  {
    href: '/resources/ruflo-ai',
    label: 'Ruflo AI',
    eyebrow: 'Guide',
    title: 'Ruflo AI as a hosted multi-agent workspace',
    summary:
      'A practical overview of what Ruflo AI is, where it fits, and why teams use a hosted layer instead of stopping at a GitHub README.',
    definition:
      'Ruflo AI is a hosted product surface for Ruflo-style agent orchestration. It packages goal planning, multi-agent delegation, memory, RAG, checkout, provisioning, and console access into a service customers can start using quickly.',
    sections: [
      {
        title: 'What Ruflo AI helps with',
        body:
          'Ruflo AI is useful when a team wants agent work to become repeatable. Instead of asking one model to do everything in one conversation, the workflow can separate planning, execution, review, and memory.',
        bullets: ['Codebase planning and implementation review', 'Research workflows with memory and retrieval', 'Team handoff between Codex, Claude Code, and a hosted UI'],
      },
      {
        title: 'Why hosted matters',
        body:
          'Open source is great for control. Hosted Ruflo is useful when the customer wants a clean purchase path, a working console, and a managed launch sequence before investing in full self-hosting.',
      },
    ],
    checklist: ['Clear model route', 'Concrete first workflow', 'Workspace count that matches the team', 'Plan and billing cycle selected before checkout'],
    conclusion:
      'Start with the hosted service when you want to validate real Ruflo usage quickly, then use the source project for deeper technical evaluation.',
    faqs: [
      {
        question: 'Is Ruflo AI a chatbot?',
        answer:
          'No. The value is orchestration: goals, multiple agent roles, memory, tools, and review workflows around real work.',
      },
      {
        question: 'Who should use it first?',
        answer:
          'Teams already experimenting with AI coding or research agents usually see the fit fastest because they already feel the pain of scattered sessions.',
      },
      {
        question: 'What should I buy first?',
        answer:
          'Growth yearly is the default because it gives enough capacity to test repeat workflows and receives the 50% annual discount.',
      },
    ],
  },
  {
    href: '/resources/how-to-use-ruflo',
    label: 'How to Use',
    eyebrow: 'Guide',
    title: 'How to use Ruflo for the first real workflow',
    summary:
      'A concise operating guide for choosing the right first goal, launching a workspace, and getting useful work out of Ruflo without overcomplicating the setup.',
    definition:
      'Using Ruflo well starts with a repeatable goal. The system is strongest when a task benefits from planning, tool use, memory, and review, rather than a one-off answer.',
    sections: [
      {
        title: 'Pick a workflow with a real loop',
        body:
          'Good first tasks include codebase audit, release checklist generation, pull request review, implementation planning, source comparison, or recurring research. Avoid vague goals such as "make the project better" until you have a clearer target.',
        bullets: ['Name the repository or source area', 'Define what a good result looks like', 'Decide which steps need human review'],
      },
      {
        title: 'Launch with the default commercial path',
        body:
          'Choose the Growth plan, keep yearly billing selected for the 50% discount, pick the model route that matches your tool preference, and continue through hosted checkout.',
      },
      {
        title: 'Review before repeating',
        body:
          'After the first run, decide what should become reusable memory, what should stay manual, and what needs a stronger review gate next time.',
      },
    ],
    checklist: ['One specific goal', 'One connected entrypoint', 'One human reviewer', 'One follow-up run to test whether memory helped'],
    conclusion:
      'The first successful Ruflo workflow should be small enough to review and important enough to repeat.',
    faqs: [
      {
        question: 'What is the easiest first use case?',
        answer:
          'A codebase review or implementation plan is usually a strong first task because the success criteria are concrete and the review path is obvious.',
      },
      {
        question: 'Should I start with all integrations enabled?',
        answer:
          'No. Start with one entrypoint, prove the loop, then add more tools once the workflow has earned the extra surface area.',
      },
      {
        question: 'What makes a Ruflo run worth repeating?',
        answer:
          'A run is worth repeating when it produced a reviewed outcome and taught the workspace something useful for the next similar task.',
      },
    ],
  },
  {
    href: '/resources/ruflo-github',
    label: 'GitHub',
    eyebrow: 'Guide',
    title: 'Ruflo GitHub guide for evaluating the source project',
    summary:
      'Use this guide to inspect the Ruflo repository with a buyer mindset: architecture, setup path, issue quality, and whether the workflow matches your team.',
    definition:
      'The Ruflo GitHub repository is the public source reference. A useful evaluation reads beyond the headline and checks how the project handles agents, plugins, memory, RAG, UI, and developer workflow integration.',
    primaryAction: {
      label: 'Open Ruflo on GitHub',
      href: sourceRepositoryHref,
      external: true,
    },
    sections: [
      {
        title: 'What to inspect first',
        body:
          'Read the README, setup steps, examples, package layout, UI notes, and any documentation around Claude Code, Codex, memory, RAG, plugins, or multi-agent coordination.',
        bullets: ['Look for clear install and run instructions', 'Check whether the agent roles are understandable', 'Read recent issues for repeated setup or integration friction'],
      },
      {
        title: 'How to compare wrappers',
        body:
          'A hosted Ruflo service should add a commercial and operational layer. It should not pretend the source project disappears; it should make evaluation, checkout, launch, and follow-up easier.',
      },
    ],
    checklist: ['Clear architecture', 'Reasonable setup path', 'Active issue signal', 'Workflow fit for your actual team'],
    conclusion:
      'Use GitHub for technical confidence and hosted Ruflo for a faster path to a paid, working service surface.',
    faqs: [
      {
        question: 'Is GitHub enough to use Ruflo?',
        answer:
          'It can be enough for technical teams ready to self-host. Hosted Ruflo exists for customers who want a managed purchase and launch path.',
      },
      {
        question: 'What is the most important source signal?',
        answer:
          'Look for concrete workflows and integration points, not just broad claims about autonomy.',
      },
      {
        question: 'Should I fork first or launch hosted first?',
        answer:
          'Launch hosted first when you want to validate the operating model quickly. Fork first when infrastructure ownership is the main requirement.',
      },
    ],
  },
  {
    href: '/resources/ruflo-reddit',
    label: 'Reddit',
    eyebrow: 'Guide',
    title: 'Ruflo Reddit research without mistaking hype for evidence',
    summary:
      'A practical way to use Reddit and community discussion while evaluating Ruflo, without treating upvotes or hot takes as a substitute for source review.',
    definition:
      'Ruflo Reddit research is useful for discovering objections, setup friction, comparisons, and user language. It should be paired with GitHub review and a small real workflow test.',
    sections: [
      {
        title: 'What community threads are good for',
        body:
          'Discussion can reveal what users are confused by, which alternatives they compare against, and whether the value proposition is landing with real builders.',
        bullets: ['Collect repeated objections', 'Watch for concrete setup reports', 'Separate first impressions from long-term usage'],
      },
      {
        title: 'What Reddit cannot prove',
        body:
          'A thread cannot prove that Ruflo fits your repository, security boundary, or team workflow. Use discussion as input, then validate with source review and a small hosted test.',
      },
    ],
    checklist: ['Repeated concrete feedback', 'Named alternatives', 'Recent setup reports', 'Evidence from people who actually ran workflows'],
    conclusion:
      'Use Reddit to sharpen questions, not to outsource the decision.',
    faqs: [
      {
        question: 'Should I trust Reddit comments about Ruflo?',
        answer:
          'Trust patterns more than individual comments. A repeated issue is worth investigating; a single dramatic opinion is not a decision.',
      },
      {
        question: 'What should I search for?',
        answer:
          'Search for Ruflo, Claude Code, Codex, multi-agent coding, RAG memory, and hosted agent workflow comparisons.',
      },
      {
        question: 'What comes after community research?',
        answer:
          'Pick one real workflow and test whether Ruflo improves planning, execution, memory, or review compared with your current process.',
      },
    ],
  },
  {
    href: '/resources/ruflo-codex',
    label: 'Codex',
    eyebrow: 'Guide',
    title: 'Ruflo and Codex for structured repository work',
    summary:
      'How to think about Ruflo alongside Codex when the goal is not just editing files, but coordinating plans, reviews, memory, and repeatable delivery.',
    definition:
      'Codex is strong at codebase work. Ruflo can add orchestration around it: goal planning, multi-agent roles, review checkpoints, and memory that helps similar work later.',
    sections: [
      {
        title: 'Where Codex fits',
        body:
          'Use Codex for concrete implementation, debugging, test fixes, and code review. Use Ruflo around that work when you need to divide roles, preserve state, and coordinate repeated tasks.',
        bullets: ['Implementation worker', 'Reviewer or verifier', 'Repository explorer', 'Release note and handoff assistant'],
      },
      {
        title: 'Where Ruflo adds leverage',
        body:
          'Ruflo is most useful when the team wants to turn one good run into a pattern: what context mattered, which review checks were useful, and which steps should happen again.',
      },
    ],
    checklist: ['Specific repository goal', 'Clear worker and reviewer roles', 'Tests or acceptance criteria', 'Memory note after the run'],
    conclusion:
      'Use Ruflo with Codex when a repository workflow deserves structure beyond a single agent session.',
    faqs: [
      {
        question: 'Does Ruflo run Codex for me?',
        answer:
          'The hosted product is designed as an orchestration and workspace layer. The exact integration path depends on the entrypoint and workspace configuration you choose.',
      },
      {
        question: 'What Codex tasks fit best?',
        answer:
          'Tasks with clear files, tests, and review criteria are strongest. Ruflo helps coordinate the surrounding planning and follow-up.',
      },
      {
        question: 'Why not only use Codex?',
        answer:
          'Only use Codex when the task is simple. Add Ruflo when the workflow repeats, needs memory, or involves several roles.',
      },
    ],
  },
  {
    href: '/resources/ruflo-claude-code',
    label: 'Claude Code',
    eyebrow: 'Guide',
    title: 'Ruflo and Claude Code for agent delegation',
    summary:
      'A guide for teams using Claude Code who want a more structured way to plan, delegate, review, and preserve successful workflows.',
    definition:
      'Claude Code can be a powerful coding entrypoint. Ruflo adds an operating model around it so planning, memory, RAG, and multi-agent review can become part of the workflow.',
    sections: [
      {
        title: 'Use Claude Code for hands-on work',
        body:
          'Claude Code fits implementation, refactoring, debugging, and exploratory repository changes. Ruflo helps decide how that work is planned, reviewed, remembered, and repeated.',
        bullets: ['Planner role defines the goal', 'Worker role executes scoped changes', 'Reviewer role checks behavior and risk'],
      },
      {
        title: 'Keep the loop reviewable',
        body:
          'The best Claude Code plus Ruflo workflows keep acceptance criteria visible. Human review should remain part of the path when repository changes affect customers, payment, security, or infrastructure.',
      },
    ],
    checklist: ['Scoped codebase target', 'Review owner', 'Rollback or verification path', 'Reusable note after completion'],
    conclusion:
      'Ruflo is the structure around Claude Code when your team wants repeatable agent delegation rather than isolated sessions.',
    faqs: [
      {
        question: 'Is Claude Code required?',
        answer:
          'No. It is one strong entrypoint. Ruflo can also be evaluated with Codex or the hosted UI depending on your team.',
      },
      {
        question: 'What makes the combination useful?',
        answer:
          'Claude Code handles concrete coding work; Ruflo helps coordinate goals, roles, memory, and review.',
      },
      {
        question: 'Should every task use multiple agents?',
        answer:
          'No. Use multiple roles when the task has planning, execution, and review complexity that justifies the structure.',
      },
    ],
  },
  {
    href: '/resources/is-ruflo-legit',
    label: 'Legit Check',
    eyebrow: 'Guide',
    title: 'Is Ruflo legit? A practical evaluation checklist',
    summary:
      'A grounded checklist for deciding whether Ruflo is worth testing, buying, or self-hosting, based on source evidence and workflow fit.',
    definition:
      'A legitimate evaluation asks whether Ruflo has clear source material, understandable architecture, realistic workflows, visible tradeoffs, and a path that matches your team. It does not rely on hype alone.',
    sections: [
      {
        title: 'Evidence to look for',
        body:
          'Start with public source, setup clarity, issue history, documentation quality, and whether the project describes concrete agent workflows such as plugins, memory, RAG, UI, Claude Code, or Codex integration.',
        bullets: ['Public repository and issue trail', 'Specific workflow descriptions', 'Realistic setup and integration notes'],
      },
      {
        title: 'Risk signs',
        body:
          'Be careful if a tool promises full autonomy without showing boundaries, review loops, setup details, or a clear explanation of where data and credentials go.',
      },
      {
        title: 'Best validation test',
        body:
          'Use one small but real workflow. If Ruflo improves planning, delegation, review, or memory enough to repeat the process, it has earned further evaluation.',
      },
    ],
    checklist: ['Can you inspect the source?', 'Can you name the first workflow?', 'Can you review the output?', 'Can the next run reuse anything useful?'],
    conclusion:
      'Ruflo is worth taking seriously when the source and the workflow both stand up to review. The safest first step is a small hosted test with clear success criteria.',
    faqs: [
      {
        question: 'Is Ruflo legit just because it is on GitHub?',
        answer:
          'No. GitHub is a starting point, not proof. You still need to inspect the architecture, issues, setup path, and workflow fit.',
      },
      {
        question: 'What is the strongest positive signal?',
        answer:
          'A successful real workflow that your team can review and repeat is stronger than any star count or social post.',
      },
      {
        question: 'What is the safest buying path?',
        answer:
          'Use the default Growth yearly plan only after you have a concrete workflow in mind and understand what hosted service is adding over self-hosting.',
      },
    ],
  },
  {
    href: '/resources/ruflo-ui',
    label: 'UI',
    eyebrow: 'Guide',
    title: 'Ruflo UI for goal planning, review, and workspace operations',
    summary:
      'What a useful Ruflo UI should do: make goals, agent roles, memory, checkout, and workspace state easier to operate without hiding important review details.',
    definition:
      'Ruflo UI is the customer-facing surface for making orchestration usable. It should help users choose a plan, launch a workspace, track state, and return to the next action quickly.',
    sections: [
      {
        title: 'What the UI should make obvious',
        body:
          'A good UI shows the goal, selected model route, workspace count, billing cycle, launch status, and next action. It should not bury the purchase path or require users to decode infrastructure details first.',
        bullets: ['Selected plan and annual discount', 'Workspace status and console access', 'Clear path back after checkout'],
      },
      {
        title: 'What belongs behind the scenes',
        body:
          'Implementation details such as D1, Workers, secrets, and payment provider APIs should be reliable, but they do not need to become visible product copy.',
      },
    ],
    checklist: ['Launch action above the fold', 'Default Growth yearly plan', 'Clear checkout return path', 'Useful console after payment'],
    conclusion:
      'The Ruflo UI should reduce hesitation: understand the value, choose the plan, pay, and return to the workspace path without friction.',
    faqs: [
      {
        question: 'Why is the first screen product-led?',
        answer:
          'Buyers need to feel the workflow immediately. A usable model and launch surface converts better than a long explanation before the first action.',
      },
      {
        question: 'Should the UI show every technical detail?',
        answer:
          'No. Show what helps the buyer decide and operate. Keep infrastructure details in docs, console logs, or admin surfaces.',
      },
      {
        question: 'What does a good checkout return do?',
        answer:
          'It returns the customer to the site with enough state to continue, confirm success, and move into provisioning or console follow-up.',
      },
    ],
  },
  {
    href: '/resources/hosted-multi-agent-workspaces',
    label: 'Hosted Workspaces',
    eyebrow: 'Guide',
    title: 'Hosted multi-agent workspaces: when they beat isolated AI chats',
    summary:
      'A practical guide to hosted multi-agent workspaces: what they coordinate, when they are worth paying for, and how to evaluate them before rollout.',
    definition:
      'A hosted multi-agent workspace is a managed place to run repeatable agent work with goals, roles, memory, review, checkout, and operational follow-up. It is useful when the team needs a shared workflow rather than another private chat tab.',
    keywords: [
      'hosted multi-agent workspaces',
      'hosted Ruflo workspace',
      'multi-agent workspace',
      'AI agent workspace',
      'agent orchestration workspace',
    ],
    sections: [
      {
        title: 'What the workspace should coordinate',
        body:
          'The workspace should keep the goal, agent roles, model route, memory, review state, and next action visible enough that a teammate can understand the run after it happens.',
        bullets: ['Goal and acceptance criteria', 'Planner, worker, reviewer, and handoff roles', 'Workspace status after checkout or provisioning'],
      },
      {
        title: 'When hosted is the right first move',
        body:
          'Hosted workspaces make sense when the team wants to validate the operating model quickly. Self-hosting can still come later, but the first decision is whether the workflow improves real work.',
      },
      {
        title: 'How to evaluate a provider',
        body:
          'Look for clear pricing, a return path after payment, visible support, privacy and terms pages, and enough product detail to know what happens before and after workspace launch.',
      },
    ],
    checklist: ['One repeatable workflow', 'Named review owner', 'Clear workspace count', 'Documented checkout and support path'],
    conclusion:
      'Choose a hosted multi-agent workspace when the team needs repeatable operation, not just a more impressive single prompt.',
    faqs: [
      {
        question: 'Is a hosted multi-agent workspace only for large teams?',
        answer:
          'No. Small teams and solo builders can benefit when they repeatedly switch between planning, implementation, review, and handoff.',
      },
      {
        question: 'What is the biggest risk?',
        answer:
          'The biggest risk is adding orchestration before the workflow is real. Start with one repeatable task and prove the review loop.',
      },
      {
        question: 'How does Ruflo AI fit this category?',
        answer:
          'Ruflo AI packages the hosted launch path, pricing, console, Codex or Claude Code entrypoints, memory, and review workflow around Ruflo-style orchestration.',
      },
    ],
  },
  {
    href: '/resources/multi-agent-coding-workflows',
    label: 'Coding Workflows',
    eyebrow: 'Guide',
    title: 'Multi-agent coding workflows for planning, implementation, and review',
    summary:
      'How to structure multi-agent coding workflows so they help real repository work instead of turning into noisy parallel chat sessions.',
    definition:
      'A multi-agent coding workflow separates repository work into clear roles. A planner scopes the task, a worker changes or investigates the code, a reviewer checks behavior and risk, and memory preserves the useful pattern for the next run.',
    keywords: [
      'multi-agent coding workflows',
      'multi-agent coding',
      'AI coding workflow',
      'repository workflow',
      'agent code review',
    ],
    sections: [
      {
        title: 'Start with the shape of the work',
        body:
          'Do not start by adding agents. Start by naming the work shape: triage, implementation plan, refactor, test repair, release preparation, or pull request review.',
        bullets: ['Triage needs exploration and prioritization', 'Implementation needs files, tests, and acceptance criteria', 'Review needs risk checks and reproducible verification'],
      },
      {
        title: 'Assign roles that reduce ambiguity',
        body:
          'A good role explains what the agent should produce and what it should avoid. Planner, worker, reviewer, and verifier are often enough for the first workflow.',
      },
      {
        title: 'Keep the human review point explicit',
        body:
          'Repository changes can affect customers, infrastructure, payment, security, or data. A useful workflow keeps review visible instead of treating agent output as automatically safe.',
      },
    ],
    checklist: ['Repository or module named', 'Agent roles assigned', 'Tests or checks identified', 'Follow-up memory note captured'],
    conclusion:
      'A multi-agent coding workflow is strongest when every role has a concrete output and the final result remains reviewable by a human.',
    faqs: [
      {
        question: 'When should I avoid multi-agent coding?',
        answer:
          'Avoid it for tiny edits where one focused coding session is faster and easier to review.',
      },
      {
        question: 'Can Codex or Claude Code be one of the roles?',
        answer:
          'Yes. Codex or Claude Code can act as implementation, debugging, review, or repository exploration entrypoints inside a larger Ruflo workflow.',
      },
      {
        question: 'What makes the workflow repeatable?',
        answer:
          'The workflow becomes repeatable when the goal, review checks, files, and lessons are clear enough to reuse on a similar task.',
      },
    ],
  },
  {
    href: '/resources/ai-agent-memory-rag',
    label: 'Memory and RAG',
    eyebrow: 'Guide',
    title: 'AI agent memory and RAG for repeatable Ruflo workflows',
    summary:
      'A grounded guide to using memory and RAG in agent workspaces without turning retrieval into clutter or trusting stale context blindly.',
    definition:
      'AI agent memory preserves stable context from previous runs, while RAG retrieves relevant material when a task needs source-backed context. In Ruflo-style workflows, both should support planning and review rather than replace human judgment.',
    keywords: [
      'AI agent memory',
      'RAG workflow',
      'memory and RAG',
      'agent memory',
      'Ruflo memory',
      'retrieval augmented agent workflow',
    ],
    sections: [
      {
        title: 'What belongs in memory',
        body:
          'Memory should store durable facts, decisions, operating preferences, and review lessons. It should not become a dumping ground for every message from every run.',
        bullets: ['Stable repository conventions', 'Decision records and review rules', 'Reusable prompts or workflow notes'],
      },
      {
        title: 'What belongs in retrieval',
        body:
          'RAG is better for source material that may be long, specific, or changing: documentation, implementation notes, issue threads, research briefs, and policy text.',
      },
      {
        title: 'How to reduce stale-context risk',
        body:
          'Ask the workflow to cite which memory or source influenced the answer. For high-impact changes, verify against current files or current source pages before acting.',
      },
    ],
    checklist: ['Separate durable memory from source retrieval', 'Record why a memory matters', 'Review stale or conflicting context', 'Keep citations visible for important claims'],
    conclusion:
      'Memory and RAG are valuable when they make the next Ruflo run faster and easier to review, not when they simply add more hidden context.',
    faqs: [
      {
        question: 'Is memory the same as RAG?',
        answer:
          'No. Memory is durable workspace context. RAG retrieves source material for a task. The best workflows use both deliberately.',
      },
      {
        question: 'What should not be stored as memory?',
        answer:
          'Avoid secrets, temporary guesses, noisy logs, and claims that will quickly expire unless there is a clear retention reason.',
      },
      {
        question: 'Why does Ruflo mention memory so often?',
        answer:
          'Ruflo is aimed at repeat workflows. Memory is one of the main ways a second run can become better than the first.',
      },
    ],
  },
  {
    href: '/resources/goal-planner-ui',
    label: 'Goal Planner UI',
    eyebrow: 'Guide',
    title: 'Goal Planner UI for agent workspaces',
    summary:
      'What a Goal Planner UI should capture before an agent run starts, and how it helps teams avoid vague prompts and unreviewable outputs.',
    definition:
      'A Goal Planner UI is the structured launch surface for an agent workflow. It turns a broad intention into a goal, role split, model route, workspace note, review checkpoint, and next action.',
    keywords: [
      'Goal Planner UI',
      'agent goal planner',
      'AI workflow planner',
      'Ruflo UI',
      'workspace goal planning',
    ],
    sections: [
      {
        title: 'Inputs that matter before launch',
        body:
          'The planner should capture the repository or source area, the goal, the expected artifact, the model or entrypoint, and the review owner before checkout or execution begins.',
        bullets: ['Goal and output format', 'Model or coding entrypoint', 'Acceptance criteria and review owner'],
      },
      {
        title: 'What the UI should not hide',
        body:
          'A polished UI is not enough. Users still need to see pricing, workspace count, payment status, provisioning state, and where to return after checkout.',
      },
      {
        title: 'How it improves agent results',
        body:
          'Good planning reduces vague prompts. It gives the agent enough boundaries to produce something reviewable and gives the team a consistent way to repeat the workflow.',
      },
    ],
    checklist: ['Specific goal', 'Expected artifact', 'Selected entrypoint', 'Visible review checkpoint'],
    conclusion:
      'A Goal Planner UI earns its place when it makes the first run clearer and the second run easier to repeat.',
    faqs: [
      {
        question: 'Is a Goal Planner UI just a prompt form?',
        answer:
          'No. A useful planner captures operational choices as well as prompt text: route, capacity, review, checkout state, and follow-up.',
      },
      {
        question: 'What should the first goal look like?',
        answer:
          'It should be small enough to review and important enough to repeat, such as a codebase audit or release readiness check.',
      },
      {
        question: 'How does Ruflo AI use this idea?',
        answer:
          'Ruflo AI puts model route, workspace launch, checkout, and follow-up in the same product surface so the workflow is not scattered across tools.',
      },
    ],
  },
  {
    href: '/resources/codebase-planning-review',
    label: 'Codebase Review',
    eyebrow: 'Guide',
    title: 'Codebase planning and review with Ruflo, Codex, and Claude Code',
    summary:
      'A practical operating model for using Ruflo around codebase planning, implementation review, release checks, and repository handoff.',
    definition:
      'Codebase planning and review is the workflow of turning a repository goal into scoped work, checking the result against acceptance criteria, and preserving the useful context for future runs.',
    keywords: [
      'codebase planning',
      'repository review',
      'implementation review',
      'Codex codebase workflow',
      'Claude Code review workflow',
    ],
    sections: [
      {
        title: 'Plan before touching files',
        body:
          'A strong run starts by mapping the target area, identifying likely files, naming the risk, and deciding what verification will count as done.',
        bullets: ['Target module or route', 'Expected files or systems', 'Tests, screenshots, build, or manual checks'],
      },
      {
        title: 'Use coding agents where they are strongest',
        body:
          'Codex and Claude Code are strongest when the task has concrete files and checks. Ruflo helps coordinate the surrounding plan, role split, review checkpoint, and memory.',
      },
      {
        title: 'Write the handoff while context is fresh',
        body:
          'A useful handoff includes what changed, what was verified, what remains risky, and which note should become memory for the next related task.',
      },
    ],
    checklist: ['Plan written first', 'Acceptance criteria named', 'Reviewer role assigned', 'Verification and handoff recorded'],
    conclusion:
      'Use Ruflo around codebase planning when the hard part is keeping the coding work scoped, reviewable, and reusable.',
    faqs: [
      {
        question: 'Is this only for pull requests?',
        answer:
          'No. It also fits audits, refactor planning, migration checks, release readiness, and debugging workflows.',
      },
      {
        question: 'Should the agent decide the review criteria?',
        answer:
          'The agent can propose criteria, but the team should confirm them before relying on the result.',
      },
      {
        question: 'What should become memory after a codebase review?',
        answer:
          'Store stable conventions, useful checks, decisions, and known risk areas, not every temporary detail from the run.',
      },
    ],
  },
  {
    href: '/resources/team-agent-operations',
    label: 'Agent Ops',
    eyebrow: 'Guide',
    title: 'Team agent operations for hosted Ruflo workspaces',
    summary:
      'How teams can turn agent experiments into an operating model with owners, workspace capacity, review rules, billing, and support paths.',
    definition:
      'Team agent operations is the practice of deciding how agents are launched, paid for, reviewed, supported, and improved across people and repositories. It matters once agent work moves beyond private experiments.',
    keywords: [
      'team agent operations',
      'agent operations',
      'AI agent ops',
      'hosted Ruflo team workflow',
      'agent workflow management',
    ],
    sections: [
      {
        title: 'Decisions to make before rollout',
        body:
          'Teams should decide who can launch a workspace, which plan matches expected usage, who reviews output, and how support or payment issues are handled.',
        bullets: ['Workspace owner', 'Review owner', 'Billing contact', 'Support path'],
      },
      {
        title: 'What to standardize first',
        body:
          'Standardize the first few repeat workflows: codebase review, research brief, implementation plan, release checklist, or source comparison. Do not standardize every possible use case on day one.',
      },
      {
        title: 'How to know operations are improving',
        body:
          'Look for faster repeat runs, clearer review notes, fewer lost decisions, and a smoother path from plan selection to checkout to provisioning follow-up.',
      },
    ],
    checklist: ['Named owner for each workspace', 'Clear plan and capacity', 'Review rule for high-impact work', 'Support and payment path documented'],
    conclusion:
      'Team agent operations turn Ruflo from a demo into a repeatable service your team can buy, revisit, and improve.',
    faqs: [
      {
        question: 'When does a team need agent operations?',
        answer:
          'A team needs it when multiple people run agent work, payment is involved, or results must be reviewed and repeated.',
      },
      {
        question: 'Which Ruflo AI plan fits agent operations first?',
        answer:
          'Growth is the common starting plan because it gives five workspaces and enough room to test team workflows.',
      },
      {
        question: 'What should not be centralized too early?',
        answer:
          'Do not centralize every prompt or every experiment. Start with repeat workflows that have clear review value.',
      },
    ],
  },
]

export const guideContent: Record<GuideChannel, GuideContent> = {
  telegram: {
    title: 'Claude Code entrypoint',
    steps: [
      'Choose the Claude Code workspace or project you want Ruflo to coordinate first.',
      'Prepare the repository goal, review boundary, and any credentials your team authorizes for the run.',
      'Continue to checkout so the hosted workspace can keep that entrypoint ready for provisioning.',
    ],
    tokenLabel: 'Claude Code workspace note',
    tokenPlaceholder: 'Repository, branch, or launch note',
    phone: {
      avatar: 'CC',
      name: 'Claude Code',
      subtitle: 'Coding entrypoint',
      lead: { text: 'Start with a scoped repository goal and a review owner.', time: '10:14', tone: 'incoming' },
      quickActions: [
        { title: 'Plan goal', subtitle: 'Define planner and reviewer roles' },
        { title: 'Open repo', subtitle: 'Prepare the first workspace target' },
      ],
      outgoing: { text: 'I want Ruflo to coordinate the first codebase review.', time: '10:16', tone: 'outgoing' },
      reply: { text: 'Add the workspace note, then continue to the Ruflo launch plan.', time: '10:17', tone: 'incoming' },
      composer: 'Paste launch note',
    },
  },
  discord: {
    title: 'Codex entrypoint',
    steps: [
      'Choose the repository workflow you want Codex to handle inside the Ruflo operating loop.',
      'Define whether Codex should explore, implement, review, or verify.',
      'Save a short launch note so the workspace starts with the right role and acceptance criteria.',
    ],
    tokenLabel: 'Codex launch note',
    tokenPlaceholder: 'Repo goal, tests, or acceptance criteria',
    phone: {
      avatar: 'CX',
      name: 'Codex',
      subtitle: 'Repository workflow',
      lead: { text: 'Pick a concrete repo task before adding more agents.', time: '09:42', tone: 'incoming' },
      quickActions: [
        { title: 'Explore', subtitle: 'Map the codebase first' },
        { title: 'Implement', subtitle: 'Assign a scoped change' },
      ],
      outgoing: { text: 'Codex should implement after Ruflo writes the plan.', time: '09:44', tone: 'outgoing' },
      reply: { text: 'Save the acceptance criteria and continue to pricing.', time: '09:45', tone: 'incoming' },
      composer: 'Paste Codex note',
    },
  },
  whatsapp: {
    title: 'Ruflo UI entrypoint',
    steps: [
      'Use the hosted UI when you want goal planning, checkout, provisioning, and console access in one place.',
      'Describe the first workflow in plain language and decide who reviews the output.',
      'Launch the workspace with the default yearly Growth plan or adjust capacity before checkout.',
    ],
    tokenLabel: 'Ruflo UI launch note',
    tokenPlaceholder: 'First workflow to run',
    phone: {
      avatar: 'UI',
      name: 'Ruflo UI',
      subtitle: 'Hosted workspace',
      lead: { text: 'A good first workflow is specific enough to review.', time: '11:03', tone: 'incoming' },
      quickActions: [
        { title: 'Goal planner', subtitle: 'Split the work into roles' },
        { title: 'Console', subtitle: 'Track checkout and provisioning' },
      ],
      outgoing: { text: 'I want the first workflow to be a repo audit.', time: '11:05', tone: 'outgoing' },
      reply: { text: 'Add that note, keep yearly selected, and launch checkout.', time: '11:06', tone: 'incoming' },
      composer: 'Paste workflow note',
    },
  },
}

export const initialGuideInputs: Record<GuideChannel, string> = {
  telegram: '',
  discord: '',
  whatsapp: '',
}

export const initialAuthForm: AuthFormState = {
  name: '',
  email: '',
  password: '',
}

export const initialCreateUserForm: CreateUserFormState = {
  name: '',
  email: '',
  password: '',
  role: 'operator',
}

export { annualBillingMultiplier }
